export default {
  darkMode: "class",
  content: ['./app/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      colors: {
        primary: '#0ea5a4',
        'card-bg': 'var(--color-bg-card)',
        'card-bg-hover': 'var(--color-bg-card-hover)',
        'card-border': 'var(--color-border-card)',
        'card-text': 'var(--color-text-card)',
        'text-muted': 'var(--color-text-muted)',
        'bg-secondary': 'var(--color-bg-secondary)',
        'text-primary': 'var(--color-text-primary)',
        'text-secondary': 'var(--color-text-secondary)',
        'accent': 'var(--color-accent)',
        'avatar-bg': 'var(--color-bg-avatar)',
        'avatar-text': 'var(--color-text-avatar)',
        'skeleton-bg': 'var(--color-bg-skeleton)',
        'button-secondary-bg': 'var(--color-bg-button-secondary)',
        'button-secondary-bg-hover': 'var(--color-bg-button-secondary-hover)',
        'button-secondary-border': 'var(--color-border-button)',
        'button-hover-bg': 'var(--color-bg-button-hover)',
        'text-nav': 'var(--color-text-nav)',
        'text-dropdown': 'var(--color-text-dropdown)',
        'bg-dropdown': 'var(--color-bg-dropdown)',
        'border-dropdown': 'var(--color-border-dropdown)',
        'bg-dropdown-hover': 'var(--color-bg-dropdown-hover)',
        'text-logo-main': 'var(--color-text-logo-main)',
        'text-logo-sub': 'var(--color-text-logo-sub)',
        'bg-footer': 'var(--color-bg-footer)',
        'border-footer': 'var(--color-border-footer)',
        'border-footer-grey': 'var(--color-border-footer-grey)',
        'text-footer': 'var(--color-text-footer)',
        'text-footer-sub': 'var(--color-text-footer-sub)',
        'text-footer-heading': 'var(--color-text-footer-heading)',
        'bg-footer-divider': 'var(--color-bg-footer-divider)',
        'bg-footer-divider-subtle': 'var(--color-bg-footer-divider-subtle)',
        'border-footer-bottom': 'var(--color-border-footer-bottom)',
        'bg-code': 'var(--color-bg-code)',
        'border-code': 'var(--color-border-code)',
        'text-code': 'var(--color-text-code)',
      }
    }
  },
  plugins: [],
}
